services:
  line-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LINE_CHANNEL_TOKEN=${LINE_CHANNEL_TOKEN}
      - OPEN_AI_MODEL=${OPEN_AI_MODEL}
      - OPEN_AI_TEMPERATURE=${OPEN_AI_TEMPERATURE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    container_name: line-bot-service