line:
  bot:
    channel-token: ${LINE_CHANNEL_TOKEN}
    channel-secret: ${LINE_CHANNEL_SECRET}
    handler:
      path: /callback

# 2) Spring AI / OpenAI
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      http:
        connect-timeout: 100s
        read-timeout: 120s
      chat:
        options:
          model: ${OPEN_AI_MODEL}
          temperature: ${OPEN_AI_TEMPERATURE}
      image:
        options:
          model: dall-e-3
          size: 1024x1024
          quality: standard
    retry:
      max-attempts: 3
      backoff:
        initial-interval: 2s
management:
  endpoints:
    web:
      exposure:
        include: health
openai:
  system-prompt: |
    你是一個 LINE AI 翻譯助手，如果收到越南文請翻譯成繁體中文、收到中文請翻譯成越南文，不用多回復其他東西，語氣親切簡單回覆即可。