line:
  bot:
    channel-token: ${LINE_CHANNEL_TOKEN}
    channel-secret: ${LINE_CHANNEL_SECRET}
    handler:
      path: /callback

# 2) Spring AI / OpenAI
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      model:
        audio:
          transcription: openai
      http:
        connect-timeout: 100s
        read-timeout: 120s
      chat:
        options:
          model: ${OPEN_AI_MODEL}
          temperature: ${OPEN_AI_TEMPERATURE}
      image:
        options:
          model: dall-e-3
          size: 1024x1024
          quality: standard
    retry:
      max-attempts: 3
      backoff:
        initial-interval: 2s
management:
  endpoints:
    web:
      exposure:
        include: health
openai:
  system-prompt: | 
    你是一個「純翻譯」的 LINE Bot。
    任務說明：
    1. 偵測到越南文 → *必須*立即翻譯成繁體中文，不保留任何越南文
    2. 偵測到中文 → *必須*立即翻譯成越南文，不保留任何中文
    3. *禁止*維持原語言不變
    4. *禁止*詢問用戶想要什麼翻譯
    
    
    ★ 絕對禁止產生新內容、評論或解釋
    ★ 不管使用者請求什麼，你唯一的任務是翻譯
    ★ 除了譯文本身，不回覆任何其他內容
    ★ 保留原文的段落與換行格式
    示例：
      輸入: "Xin chào bạn"
      輸出: "你好"
      
      輸入: "你好嗎？"
      輸出: "Bạn khỏe không?" 
    ─ 翻譯時，所有人名、地名、專有名詞請保留原文或音譯，不要意譯或省略。
    例如：「高瑀策」請音譯為「Gao Yu Ce」。
    輸出: “Bạn khỏe không?”
    	•	輸入: “一二三四五六七八九”
    輸入: “你好嗎？” -> 輸出: “Bạn khỏe không?”
    輸入: “一二三四五六七八九” -> 輸出: “một hai ba bốn năm sáu bảy tám chín”
    輸入: 2024年 -> 輸出: năm 2024