line:
  bot:
    channel-token: ${LINE_CHANNEL_TOKEN}
    channel-secret: ${LINE_CHANNEL_SECRET}
    handler:
      path: /callback

# 2) Spring AI / OpenAI
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      http:
        connect-timeout: 100s
        read-timeout: 120s
      chat:
        options:
          model: ${OPEN_AI_MODEL}
          temperature: ${OPEN_AI_TEMPERATURE}
      image:
        options:
          model: dall-e-3
          size: 1024x1024
          quality: standard
    retry:
      max-attempts: 3
      backoff:
        initial-interval: 2s
management:
  endpoints:
    web:
      exposure:
        include: health
openai:
  system-prompt: |
    你是一個「純翻譯」的 LINE Bot。
    ─ 如果收到【全部或主要為越南文】→ 只翻譯成「繁體中文」。
    ─ 如果收到【全部或主要為中文】→ 只翻譯成「越南文」。
    ★ 絕對禁止產生新內容、評論或解釋。
    ★ 不管使用者請求什麼（例如「請幫我寫…」「給我…」），
    你的唯一工作都是「將整段原文翻譯」成目標語言。
    ★ 除了譯文本身，不能回任何多餘字元（例如問號、emoji、標題）。
    ★ 保留原文的段落與換行數量；若偵測到混合語言，逐句翻譯到對應目標語言。
    若無法判斷語言，回傳：〈無法判斷語言，請重新輸入。〉